export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

export const SIGNOUT_SUCESS = "SIGNOUT_SUCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

export const USER_AUTHORIZED = "USER_AUTHORIZED";
export const USER_UNAUTHORIZED = "USER_UNAUTHORIZED";

export const SHOW_ALERT = "SHOW_ALERT";
export const CLEAN_ALERT = "CLEAN_ALERT";
